environment:
- LinkedList:
  - InsertEnd.cpp
  - notes.cpp
  - Insert.cpp
  - Reverse.cpp
  - DeleteNth.cpp
  - InsertNth.cpp
- MinHeap:
  - KthLargestInArray.cpp
  - minHeap.cpp
  - KthLargestInStream.cpp
  - min-heap.py
- Graph:
  - BFS.cpp
  - Dijkstra.cpp
  - AdjacencyListUndirectedEasy.cpp
  - word-boogle.py
  - DijkstraShortestPath.java
  - DFS.py
  - KnightWalk.cpp
  - AdjacencyListUndirected.cpp
  - BFS.py
- Trie:
  - Trie.java
  - BinarySearch.cpp
  - notes.cpp
  - missing-number-in-array.cpp
- Sort:
  - Selection.cpp
  - notes.cpp
  - MergeSorting.cpp
- String:
  - find-uncommon-characters-two-strings.cpp
  - longest-prefix-suffix.py
  - form-a-palindrome-DONTREAD.cpp
  - find-remove-characters-from-the-first-string-which-are-present-in-the-second-string.py
  - reverseString.cpp
  - 0.1-longest-substring-without-repeating-characters.py
  - word-break-problem-dp-32.cpp
  - permutationString-DONTREAD.cpp
  - reverse-words.py
  - ASCII-to-integer.py
  - resverse-each-word-in-string.py
  - recursively-remove-all-adjacent-duplicates.cpp
  - word-break.py
  - permutations-of-a-given-string.py
  - '*minimize-string-value.cpp'
  - reversing-the-vowels.py
  - 1-minimum-insertions-to-form-a-palindrome.py
  - '*permutations-of-a-given-string.cpp'
  - notes.py
  - 2-longestpalindrome.cpp
  - 0.1-smallest-distant-window.py
  - remove-minimum-number-characters-two-strings-become-anagram.py
  - check-string-can-obtained-rotating-another-string-2-places.py
  - 2-longestpalindrome.py
  - transform-string.cpp
  - '*permutations-of-a-given-string-no-inbuilt.py'
  - binary-string.py
  - notes.cpp
  - binary-string.cpp
  - reverse-string.py
  - implement-strstr.py
  - reversing-the-vowels.cpp
  - 1-longest-common-substring.py
  - 0.1-longest-substring-without-repeating-char-shotcut.py
  - '*print-possible-strings-can-made-placing-spaces.cpp'
  - balanced_paranthesis_longest.py
  - remove-minimum-number-characters-two-strings-become-anagram-2.py
  - colNameForNumberExcel.cpp
  - 1-longest-common-subsequence.py
  - balance_paranthesis.py
  - '*1-list.txt'
- Tree:
  - BT-view-top.py
  - merge-two-bst-1.cpp
  - bst.cpp
  - merge-two-bst-2.cpp
  - given-a-binary-tree-print-all-root-to-leaf-paths.cpp
  - BT-full_nodes.py
  - find-k-th-smallest-element-in-bst.cpp
  - BT-view-left_NOT_WORKING.py
  - BT-DFS.py
  - BT-BFS-levelorder.py
  - bst-sumtree.cpp
  - BT-MinDepth.py
  - count-bst-nodes.cpp
  - check-if-two-trees-are-mirror.cpp
  - tree-traversal-level-order.cpp
  - notes.cpp
  - BT-view-right.py
  - bst-validate.py
  - BT-MaxDepth.py
  - duplicate-subtree-in-BT.cpp
  - bst-maxpath.py
  - BT-Path-root-to-leaf.py
  - print-nodes-dont-sibling-binary-tree.cpp
  - BT-boundary-traversal.cpp
  - connect-nodes-at-same-level.cpp
  - BT-diameter.py
  - BT-Lowest_common_ancestor.py
  - tree-traversals-inorder-preorder-and-postorder.cpp
  - BT-count-nodes.py
  - bst-sumtree.py
- _need_to_study_hard:
  - android-unlock-pattern.py
  - build-lowest-number-by-removing-n-digits-from-a-given-number.cpp
- Array:
  - 2-count-duplets-key-pair.py
  - stock-buy-and-sell.cpp
  - '*majority-element.cpp'
  - inversions-of-array.py
  - 2-count-triplets-with-sum-smaller-that-a-given-value.py
  - reverse-an-array-upto-a-given-position.py
  - array-rotation-type.cpp
  - arrange-the-numbers-to-form-the-biggest-number.cpp
  - 2-count-quadruple-numbers-with-sum-equal-to-given-sum.py
  - 4-subarray-with-given-sum.py
  - .~c9_invoke_1rE2.py
  - 1sum-element-equal-to-the-sum-of-all-the-remaining-elements.py
  - find-minimum-difference-pair.cpp
  - count-number-of-occurrences-or-frequency-in-a-sorted-array.py
  - 2-pythagorean-triplet-in-an-unsorted-array.py
  - '*1-List.txt'
  - 4-max-sum-cont-subarray-kadane.py
  - trapping-rain-water.cpp
  - array-rotation-type.py
  - array-rotation-left.py
  - 3-a-product-formed-by-pair-in-array.py
  - notes.py
  - array-rotation-right.py
  - rearrange-positive-and-negative-numbers-publish.py
  - reverse-an-array-in-groups-of-given-size.py
  - notes.cpp
  - find-the-leaders-in-an-array.py
  - temp.py
  - find-minimum-difference-pair.py
  - 2-count-triplets-key-pair.py
  - sort-an-array-of-0s-1s-and-2s.cpp
  - find-the-leaders-in-an-array.cpp
  - find-index-first-1-sorted-array-0s-1s.cpp
  - modular-exponentiation.cpp
  - 3-a-product-array-puzzle.py
  - equilibrium-index-of-an-array.py
  - trapping-max-water.py
  - minimum_platforms.py
  - minimum-meeting_rooms.py
  - sort-an-array-of-0s-1s-and-2s.py
  - sort-a-list-with-len-of-values.py
  - minimum-platforms.cpp
  - rearrange-array-into-zig-zag-fashion.py
  - 3-return-a-pair-with-maximum-product-in-array-of-integers.py
  - rearrange-array-alternately.py
  - find-a-Missing-number-in-array.cpp
  - 2-triplet-sum-in-array.py
  - find-a-fixed-point-in-a-given-array.cpp
  - 1sum-given-two-unsorted-arrays-find-pairs-whose-sum-x.py
  - '*count-key-pair.cpp'
  - 2-count-triplets-with-zero-sum.py
  - trapping-rain-water.py
  - 4-max-sum-without-adjacents.py
  - find-item-whose-elements-before-small-after-big.py
- HashTable:
  - notes.cpp
  - HashTable.cpp
- Search:
  - BinarySearch.cpp
  - notes.cpp
- _need_to_study_medium:
  - word_ladder.py
  - longestIncresePathMatrix.py
  - count-d-digit-positive-integers-with-0.cpp
  - decode_string.py
- _leet:
  - tree: []
  - sortAndsearch:
    - divide-two-integers.py
    - mergeIntervals.py
    - Search-in-Rotated-Sorted-Array.py
    - powx-n.py
  - recursion:
    - subsets.py
    - StrobogrammaticNumber.py
    - regular-expression-matching.py
  - array:
    - Multiple-Strings.py
    - valid-palindrome.py
    - longest-substring-without-repeating-char-easy.py
    - validate-ip-address.py
    - minimum-window-substring.py
    - minimum-cost-to-hire-work.py
    - Move-Zero-InPlace.py
    - Roman-to-Integer.py
    - plusOne.py
    - 3Sum.py
    - merge-sorted-array.py
    - minimum-window-substring_Notworking.py
    - compare-string-backspace.py
    - missing_ranges.py
    - integer-to-english-words.py
    - Group-Anagrams.py
  - dynamic:
    - coin_change.py
    - split-array-k-sub-array-max-sum.py
    - word-square.py
  - 2-Dim:
    - Robot-room-cleaner.py
    - n-queens.py
    - RangeSumMatrix.py
    - word-search-board.py
    - RemoveStones.py
- python:
  - argsKargs.py
  - Chars-Not-Present-In-Second-String.py
  - FirstNonRepeatingCharacter.py
  - MapReduce.py
  - TwiceCounter.py
  - ReverseWords.py
  - ElementsOfArrayByFrequency.py
  - ListComprehensions.py
  - OddOccurance.py
  - RemoveDuplicates.py
  - stock-buy-and-sell.py
  - ListComp.py
  - RemoveSpace.py
- Z_misc:
  - learn.py
  - createTableOfContents.py
  - CheckURL.py
  - .yaml
  - lru-cache.cpp
  - url.py
  - oddNumber.cpp
  - CheckURL_Log.txt
  - environment.yaml
  - number-of-pairs.cpp
- 2-Dim:
  - find-islands.py
  - rotate-n*n-matrix-clock.py
  - possible-paths-top-left-bottom-right-nxm-matrix.cpp
  - rotate-n*n-matrix-anti-clock.py
  - flood-fill-algorithm.cpp
  - 2-d-array.cpp
  - findIslands.cpp
  - TicTacToeCheck.py
  - a-boolean-matrix-question.cpp
  - TicTacToeCheck.cpp
  - check-isolated-pixel.py
- bits:
  - position-of-rightmost-set-bit.cpp
  - count-number-of-bits-to-be-flipped-to-convert-a-to-b.cpp
  - check-bits-number-set.cpp
- _AmazonEasy:
  - replace-os-with-xs.cpp
  - converting-decimal-roman-numerals.cpp
  - interesting-method-generate-binary-numbers-1-n.py
  - check-square-root-of-an-integer.cpp
  - calculate-angle-hour-hand-minute-hand.cpp
  - write-a-c-function-to-print-the-middle-of-the-linked-list.cpp
  - numbers-unique-distinct-digits.cpp
  - replace-0-5-input-integer.py
  - 1test.py
  - converting-roman-numerals-decimal.cpp
  - check-if-a-number-can-be-expressed-as-xy-x-raised-to-power-y.cpp
  - run-length-encoding.cpp
- README.md
- .gitignore
- review.yaml
