environment:
- LinkedList:
  - cpp:
    - InsertEnd.cpp
    - notes.cpp
    - Insert.cpp
    - Reverse.cpp
    - DeleteNth.cpp
    - InsertNth.cpp
  - reverse-linked-list.py
  - 2-DoubleLinkedList.py
  - middle-of-the-linked-list.py
  - partition-linked-list.py
  - sort-linked-list.py
  - addTwoNumbers-linkedlist.py
  - 1-SinglyLinkedList.py
  - merge-two-sorted-lists-noextraspace.py
  - reorder-list-alternatively.py
- SystemDesign:
  - notes.yml
- MinHeap:
  - KthLargestInArray.cpp
  - minHeap.cpp
  - KthLargestInStream.cpp
  - min-heap.py
- Graph:
  - BFS.cpp
  - Dijkstra.cpp
  - AdjacencyListUndirectedEasy.cpp
  - word-boogle.py
  - DijkstraShortestPath.java
  - DFS.py
  - KnightWalk.cpp
  - AdjacencyListUndirected.cpp
  - BFS.py
- Z_BookmarkedToStudy:
  - _need_to_study_hard:
    - android-unlock-pattern.py
    - build-lowest-number-by-removing-n-digits-from-a-given-number.cpp
  - _need_to_study_medium:
    - word_ladder.py
    - longestIncresePathMatrix.py
    - count-d-digit-positive-integers-with-0.cpp
    - decode_string.py
  - _AmazonEasy:
    - replace-os-with-xs.cpp
    - converting-decimal-roman-numerals.cpp
    - interesting-method-generate-binary-numbers-1-n.py
    - check-square-root-of-an-integer.cpp
    - write-a-c-function-to-print-the-middle-of-the-linked-list.cpp
    - numbers-unique-distinct-digits.cpp
    - replace-0-5-input-integer.py
    - 1test.py
    - converting-roman-numerals-decimal.cpp
    - check-if-a-number-can-be-expressed-as-xy-x-raised-to-power-y.cpp
    - run-length-encoding.cpp
- Trie:
  - Trie.java
  - Trie.py
  - Trie.class
  - BinarySearch.cpp
  - notes.cpp
  - missing-number-in-array.cpp
  - Trie$TrieNode.class
- String:
  - longest-prefix-suffix.py
  - find-remove-characters-from-the-first-string-which-are-present-in-the-second-string.py
  - find-uncommon-characters-two-strings.py
  - permutations-of-a-given-string-backtracking.py
  - 0.1-longest-substring-without-repeating-characters.py
  - reverse-words.py
  - ASCII-to-integer.py
  - 2-longestpalindrome-count-backtracking.py
  - resverse-each-word-in-string.py
  - word-break.py
  - '*minimize-string-value.cpp'
  - reversing-the-vowels.py
  - 1-minimum-insertions-to-form-a-palindrome.py
  - notes.py
  - remove-minimum-number-characters-two-strings-become-anagram.py
  - check-string-can-obtained-rotating-another-string-2-places.py
  - 2-longestpalindrome.py
  - binary-string.py
  - notes.cpp
  - reverse-string.py
  - colNameForNumberExcel.py
  - implement-strstr.py
  - 1-longest-common-substring.py
  - 2-palindrome-partitioning.py
  - '*print-possible-strings-can-made-placing-spaces.cpp'
  - remove-minimum-number-characters-two-strings-become-anagram-2.py
  - 1-longest-substring-without-repeating-char-easy.py
  - 1-longest-common-subsequence.py
  - '*1-list.txt'
- Tree:
  - BT-view-top.py
  - tree-traversals-inorder-preorder-and-postorder.py
  - bst.cpp
  - BT-full_nodes.py
  - BT-DFS.py
  - BT-BFS-levelorder.py
  - merge-two-bt-sum.py
  - BT-MinDepth.py
  - connect-nodes-at-same-level.py
  - bst-kth-smallest-element.py
  - tree-traversal-level-order.cpp
  - BT-view-left.py
  - notes.cpp
  - BT-view-right.py
  - bst-validate.py
  - BT-MaxDepth.py
  - bst-maxpath.py
  - BT-boundary-traversal.py
  - BT-Path-root-to-leaf.py
  - print-nodes-dont-sibling-binary-tree.cpp
  - BT-boundary-traversal.cpp
  - tree-traversal-level-order-zig-zag.py
  - tree-traversal-build-preorder.py
  - BT-diameter.py
  - BT-Lowest_common_ancestor.py
  - BT-Path-root-to-leaf-Sum.py
  - BT-mirror-trees.py
  - tree-traversals-inorder-preorder-and-postorder.cpp
  - BT-duplicate-subtrees.py
  - BT-count-nodes.py
  - tree-traversal-level-order.py
  - bst-sumtree.py
- Array:
  - stock-buy-and-sell.cpp
  - '*majority-element.cpp'
  - inversions-of-array.py
  - 2-count-triplets-with-sum-smaller-that-a-given-value.py
  - reverse-an-array-upto-a-given-position.py
  - 2-count-duplets-key-pair-difference.py
  - 2-count-quadruple-numbers-with-sum-equal-to-given-sum.py
  - 4-subarray-with-given-sum.py
  - .~c9_invoke_1rE2.py
  - 1sum-element-equal-to-the-sum-of-all-the-remaining-elements.py
  - 4-subarray-sums-divisible-by-k.py
  - count-number-of-occurrences-or-frequency-in-a-sorted-array.py
  - 4-subarray-sum-minimum-size.py
  - 2-pythagorean-triplet-in-an-unsorted-array.py
  - 3-pairs-of-songs-with-total-durations-divisible-by-60.py
  - '*1-List.txt'
  - 4-max-sum-cont-subarray-kadane.py
  - trapping-rain-water.cpp
  - array-rotation-type.py
  - array-rotation-left.py
  - 3-a-product-formed-by-pair-in-array.py
  - notes.py
  - reorganize-string-alternatively.py
  - array-rotation-right.py
  - rearrange-positive-and-negative-numbers-publish.py
  - reverse-an-array-in-groups-of-given-size.py
  - notes.cpp
  - find-the-leaders-in-an-array.py
  - arrange-largest-number.py
  - temp.py
  - find-minimum-difference-pair.py
  - 2-count-triplets-key-pair.py
  - find-index-first-1-sorted-array-0s-1s.cpp
  - modular-exponentiation.cpp
  - stock-buy-and-sell.py
  - 3-a-product-array-puzzle.py
  - equilibrium-index-of-an-array.py
  - trapping-max-water.py
  - minimum_platforms.py
  - minimum-meeting_rooms.py
  - sort-an-array-of-0s-1s-and-2s.py
  - 2-count-duplicates-appear-twice.py
  - sort-a-list-with-len-of-values.py
  - minimum-platforms.cpp
  - rearrange-array-into-zig-zag-fashion.py
  - 3-return-a-pair-with-maximum-product-in-array-of-integers.py
  - rearrange-array-alternately.py
  - find-a-Missing-number-in-array.cpp
  - 2-triplet-sum-in-array.py
  - find-a-fixed-point-in-a-given-array.cpp
  - 1sum-given-two-unsorted-arrays-find-pairs-whose-sum-x.py
  - '*count-key-pair.cpp'
  - 2-count-triplets-with-zero-sum.py
  - trapping-rain-water.py
  - 4-max-sum-without-adjacents.py
  - 2-count-duplets-key-pair-sum.py
  - find-item-whose-elements-before-small-after-big.py
- HashTable:
  - notes.cpp
  - HashTable.cpp
- _leet:
  - conversions:
    - Multiple-Strings.py
    - Roman-to-Integer.py
    - integer-to-english-words.py
  - medium3:
    - angle-between-hands-of-a-clock.py
  - medium2:
    - jump-game.py
    - maximum-swap.py
    - single-element-in-a-sorted-array.py
    - min-deletion-cost-avoid-repeat.py
    - boats-to-save-people.py
    - number-of-connected-components-in-an-undirected-graph.py
    - minimum-path-sum-triangle.py
    - matrix-block-sum.py
    - majority-element.py
    - next-permutation.py
    - least-number-of-unique-integers-after-k-removals.py
    - diagonal-matrix-traverse.py
    - remove-duplicate-letters.py
    - spiral-matrix.py
    - k-closest-points-to-origin.py
    - triangle.py
    - spiral-matrix-ii.py
    - shortest-unsorted-continuous-subarray.py
    - remove-k-digits.py
    - shortest-bridge-dfs-bfs.py
    - non-decreasing-array.py
    - valid-sudoku.py
  - tree: []
  - bit:
    - binary-to-decimal.py
    - decode-xored-array.py
    - decimal-to-binary.py
    - steps-to-reduce-a-number-to-zero.py
    - notes.yml
    - MaxLenOfConcatStrWithUniqueChars.py
  - medium1:
    - remove-all-adjacent-duplicates.py
    - longestIncreasingSubsequence.py
    - maximum-product-subarray.py
    - top-k-frequent-elements.py
    - Evaluate-Expression-calculator.py
    - mergeIntervals-meeting-scheduler.py
    - find-peak-element.py
    - perfect_square_sums.py
    - top-k-frequent-words.py
    - combination-sum-backtracking.py
    - balanced_paranthesis_generate_backtrack.py
    - string_compression.py
    - clone-graph.py
    - course-schedule.py
    - permutations-of-string-list-backtrack.py
    - find-smallest-divisor-given-threshold.py
    - mergeIntervalListsIntersections.py
    - find-duplicate-file-in-system.py
    - balanced_paranthesis_longest.py
    - maximum-points-you-can-obtain-from-cards.py
    - task-scheduler.py
    - robot-bounded-circle.py
    - decode-ways.py
    - mergeIntervals.py
    - balance_paranthesis_return_str.py
    - minimum-time-difference.py
    - partition_labels.py
    - balance_paranthesis.py
    - balance_paranthesis_simple.py
  - sortAndsearch:
    - divide-two-integers.py
    - Search-in-Rotated-Sorted-Array.py
    - powx-n.py
  - recursion:
    - subsets.py
    - StrobogrammaticNumber.py
    - regular-expression-matching.py
  - array:
    - valid-palindrome.py
    - validate-ip-address.py
    - minimum-window-substring.py
    - minimum-cost-to-hire-work.py
    - Move-Zero-InPlace.py
    - plusOne.py
    - 3Sum.py
    - merge-sorted-array.py
    - compare-string-backspace.py
    - missing_ranges.py
    - Group-Anagrams.py
  - dynamic:
    - coin_change.py
    - split-array-k-sub-array-max-sum.py
    - word-square.py
  - design:
    - design-file-system.py
    - log-storage-system.py
    - binary-search-tree-iterator.py
    - tic-tac-toe.py
    - first-unique-number.py
    - words-data-structure.py
    - zigzag-iterator.py
    - shortest-word-distance.py
  - 2-Dim: []
- python:
  - argsKargs.py
  - Chars-Not-Present-In-Second-String.py
  - FirstNonRepeatingCharacter.py
  - MapReduce.py
  - TwiceCounter.py
  - ReverseWords.py
  - ElementsOfArrayByFrequency.py
  - ListComprehensions.py
  - OddOccurance.py
  - RemoveDuplicates.py
  - stock-buy-and-sell.py
  - ListComp.py
  - RemoveSpace.py
- Z_misc:
  - Sort:
    - Selection.cpp
    - notes.cpp
    - MergeSorting.cpp
  - Search:
    - BinarySearch.cpp
    - notes.cpp
  - learn.py
  - createTableOfContents.py
  - CheckURL.py
  - lru-cache.cpp
  - url.py
  - oddNumber.cpp
  - CheckURL_Log.txt
  - environment.yaml
  - number-of-pairs.cpp
- 2-Dim:
  - leet:
    - Robot-room-cleaner.py
    - pacific-atlantic-water-flow.py
    - number-of-provinces.py
    - minimum-path-sum-matrix.py
    - matrix-binary-search-leftmost-column-1.py
    - n-queens.py
    - matrix-binary-search.py
    - snakes-and-ladders.py
    - RangeSumMatrix.py
    - word-search-board.py
    - RemoveStones.py
    - candy-crush.py
    - maximal_square.py
  - find-islands.py
  - a-boolean-matrix.py
  - rotate-n-n-matrix-clock.py
  - possible-paths-top-left-bottom-right-nxm-matrix.py
  - 2-d-array.cpp
  - rotate-n-n-matrix-anti-clock.py
  - flood-fill-algorithm.py
  - find-islands-maxarea.py
  - TicTacToeCheck.py
  - check-isolated-pixel.py
  - findisland-rotting-oranges.py
- bits:
  - position-of-rightmost-set-bit.cpp
  - count-number-of-bits-to-be-flipped-to-convert-a-to-b.cpp
  - check-bits-number-set.cpp
- README.md
- .gitignore
- tips.yaml
- environment.yaml
- review.yaml
